#!/bin/bash
pushd /webapp/aip-web
echo remove node_modules ...
rm -rf node_modules
echo remove package-lock.json ...
rm -f package-lock.json
echo npm install ...
npm install
echo start nodejs session ...
screen -S web_session -dm npm start
pushd /webapp/aip-catalog
echo remove node_modules ...
rm -rf node_modules
echo remove package-lock.json ...
rm -f package-lock.json
echo npm install ...
npm install
echo start nodejs session ...
screen -S catalog_session -dm npm start
bash
