#!/bin/bash
pushd /webapp/node-ex-website
echo remove node_modules ...
rm -rf node_modules
echo remove package-lock.json ...
rm -f package-lock.json
echo npm install ...
npm install
echo start nodejs session ...
screen -S web_session -dm npm start
bash
